### ISSUE TITLE
How to upgrade ts-defold on existing project?

### ISSUE THREAD

**Issue by ProgrammingLife** [ts-defold/create#8]
How to properly upgrade ts-defold on existing project?

**Comment by thinknathan** [comment]
Depends on how old your project is. If it's only a few months old, a simple `npm upgrade` should get you most of the way there.

If your project is from before we introduced [tstl-trim-extensions](https://github.com/thinknathan/ts-defold-tstl-trim-extensions), you should install that plugin and then follow the update instructions in the readme of that project.

TypeScript and TypeScriptToLua are pinned more restrictively, so if you want to upgrade them you'll have to check which versions are compatible with each other. Start by upgrading TypeScriptToLua to the latest version. Then check their [changelog](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/CHANGELOG.md) or the peer dependency in their [package](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/package.json) file to see which version of TypeScript they require, and upgrade your project to use that exact version.
